"""add pattern req & inventory tables

Revision ID: ac4ac24cc91b
Revises: 6d4e406dc9da
Create Date: 2025-12-28 18:21:28.321943

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac4ac24cc91b"
down_revision: Union[str, Sequence[str], None] = "6d4e406dc9da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory",
        sa.Column("thread", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["thread"], ["threads.id"], onupdate="CASCADE"),
        sa.PrimaryKeyConstraint("thread"),
    )
    op.create_table(
        "pattern_requirements",
        sa.Column("pattern", sa.Integer(), nullable=False),
        sa.Column("thread", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pattern"],
            ["patterns.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["thread"], ["threads.id"], onupdate="CASCADE"),
        sa.PrimaryKeyConstraint("pattern", "thread"),
        sa.UniqueConstraint("pattern", "thread", name="pattern_thread_uix"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("pattern_requirements")
    op.drop_table("inventory")
